name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn requests pytest

      - name: Start FastAPI server
        run: |
          nohup uvicorn apiserver:app --host 0.0.0.0 --port 8000 --reload &
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for server to be ready
        run: sleep 10  # Increase wait time if needed

      - name: Run tests
        run: pytest testAutomation.py
